### ISSUE TITLE
upgrade to podman-machine v 0.17

### ISSUE THREAD

**Issue by tenfourty** [garethahealy/homebrew-boot2podman#1]
Hey Gareth,

This is a great repo, just testing it and I realised that you are a wee bit out of date.

Podman-machine v0.17 is now available https://github.com/boot2podman/machine/releases

Thanks and keep up the great work,

Jeremy

**Comment by garethahealy** [comment]
Hey @tenfourty - have updated master to latest: https://github.com/boot2podman/machine/releases/tag/v0.17

**Comment by tenfourty** [comment]
nice! thanks Gareth.
